spring:
  datasource:
#    url: jdbc:h2:mem:store
#    username: admin
#    password:
      url: jdbc:postgresql://localhost:5432/cyberestore2
      username: postgres
      password: 1111

#  h2:
#    console:
#      path: /h2-console
#      settings:
#        web-allow-others: true
#      enabled: true

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  #    properties:
#      hibernate.format_sql: true

#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/store
#    username: postgres
#    password: 12345

  #  h2:
  #    console:
  #      path: /h2-console
  #      settings:
  #        web-allow-others: true
  #      enabled: true

#  jpa:
#    generate-ddl: true
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#  none
#    user:
#      name: volume
#      password: volume